### ISSUE TITLE
Inconsistent pact manifest generation when using gRPC responseMetadata

### ISSUE THREAD

**Issue by ysatarov** [YOU54F/pact-ruby-ffi#6]
Hi!

We encountered a strange problem when using with gRPC and `responseMetadata`. The contents of the pact manifest in these cases depends on the order in which the tests are run.

![screenshot](https://github.com/user-attachments/assets/a9864a3b-ea59-4c72-96e7-7519490df230)

Below is a slightly modified example of area_calculator test for reproduction:
https://github.com/YOU54F/pact-ruby-ffi/commit/78a2a2af17b5567739a46c3d69e6d443c39ccfae

There are two identical tests added, one of them at the beginning and the other at the end of spec-file. The response format in the final pact manifest differs for these two added specs when running specs in random order, which leads to an error publishing contract to pact broker with pact-cli:

```
Cannot change the content of the pact for SOME-CONSUMER version 2821c525 and provider SOME_PROVIDER, as race conditions will cause unreliable results for can-i-deploy. Each pact must be published with a unique consumer version number. Some Pact libraries generate random data when a concrete value for a type matcher is not specified, and this can cause the contract to mutate - ensure you have given example values for all type matchers. For more information see https://docs.pact.io/go/versioning
```

Tried protobuf-plugin v0.4 / v0.5.4, pact-ffi v0.4.22 (linux-x86_64 and macos-aarch64), ruby v3.1.2 / v3.3.6

**Comment by YOU54F** [comment]
Hey @ysatarov.

First off nice work to you and the Kuper-Tech team for your work on sbmt-pact. I've been meaning to catch up for a while.

I took it for a spin recently and started testing it out against some of our existing ruby projects which use pact.

Needed a few tweaks as we don't use rails.

My delta is here. https://github.com/Kuper-Tech/sbmt-pact/compare/master...YOU54F:sbmt-pact:feat/pact-ruby

Anyway back to your question in point.

The order of interactions should not matter. If you do re-order them to the same as a previous publish, does that rectify the publishing issue?

Is that the only delta between runs (interaction order)?

If so, that is determined by the pact-broker on publish.

Here is where the check starts in the pact_publish api resource

https://github.com/pact-foundation/pact_broker/blob/96532124f3a53a499276c69ff2df785b8377588e/lib/pact_broker/api/resources/publish_contracts.rb#L25

which calls into the contract_service

https://github.com/pact-foundation/pact_broker/blob/96532124f3a53a499276c69ff2df785b8377588e/lib/pact_broker/contracts/service.rb#L49-L64

the calculated pact_version will be important, as it will be used to find existing pacts, by that version number.

https://github.com/pact-foundation/pact_broker/blob/96532124f3a53a499276c69ff2df785b8377588e/lib/pact_broker/contracts/service.rb#L131-L142

The Pact Broker isn't aware of the V4 Pact specification, so it may not be able to determine that these pact files are the same.

Maybe that is enough of a cookie trail to take a peek at the broker and cast your Rubyist eyes across it

**Comment by ysatarov** [comment]
> My delta is here

Thanks! It may take a little bit of time, but we'll definitely look into your changes. Feel free to send a pull request if you'd like

> Is that the only delta between runs (interaction order)?

Well, not exactly. Maybe it was the screenshot that added some confusion )
The point is the same test example using responseMetadata gives different serialization of response.contents in generated pact manifest. 

If it runs first, response.contents would be
```
...
      "response": [
        {
          "contents": {
            "content": ""
          },
         ...
        }
      ],
...
```

And if we move the same test example into the end of the spec file and run, response.contents will contain 3 more fields: 
```
...
      "response": [
        {
          "contents": {
            "content": "",
            "contentType": "application/protobuf;message=AreaResponse",
            "contentTypeHint": "BINARY",
            "encoded": "base64"
          },
         ...
        }
      ],
...
```

![screenshot1](https://github.com/user-attachments/assets/6d94b2c3-3ca5-4a2d-82b1-a6ada480384c)

**Comment by ysatarov** [comment]
> If the middle test is not there, does the same occur?

if I run only that one specific test, it generates:

```
...
      "response": [
        {
          "contents": {
            "content": "",
            "contentType": "application/protobuf;message=AreaResponse",
            "contentTypeHint": "BINARY",
            "encoded": "base64"
          },
         ...
        }
      ],
...
```

**Comment by YOU54F** [comment]
Ok, so we have for a most minimal reproduction

- 2 exact tests, executed in the same run
  - same named consumer/provider pair
  - only differ by description
  - each test creates a new pact handle

1. Moving the new_pact initializer out of the each indiv tests block so each test share a pact handle does not make a difference.
2. Swapping the order of the tests, always results in the first interaction losing some fields, transforming the first interaction from 

```json
"response": [
  {
    "contents": {
      "content": ""
    },
    "metadata": {
      "contentType": "application/protobuf;message=AreaResponse",
      "grpc-message": "Not implemented",
      "grpc-status": "UNIMPLEMENTED"
    }
  }
],
```

to 

```json
      "response": [
        {
          "contents": {
            "content": "",
            "contentType": "application/protobuf;message=.area_calculator.AreaResponse",
            "contentTypeHint": "BINARY",
            "encoded": "base64"
          },
          "metadata": {
            "contentType": "application/protobuf;message=.area_calculator.AreaResponse",
            "grpc-message": "Not implemented",
            "grpc-status": "UNIMPLEMENTED"
          }
        }
      ],
```

a diff of

```
53,56c53
<             "content": "",
<             "contentType": "application/protobuf;message=.area_calculator.AreaResponse",
<             "contentTypeHint": "BINARY",
<             "encoded": "base64"
---
>             "content": ""
```

3. If we name each provider differently, each pact is saved with the correct fully populated `response[0].contents` object
4. If we run 1 test, with a pre-existing pact containing the other interaction, the other interaction will be modified.

This leads me to believe the issue is during the pact merge process in pact-reference, the rust core.

**Comment by YOU54F** [comment]
I'll make a repro in pact-ref and make a bug report over there (or transfer this issue)

**Comment by YOU54F** [comment]
Added a failing test in pact_reference project, via the pact_ffi interface which we use as consumers in the ruby wrapper lib (and others)

https://github.com/pact-foundation/pact-reference/compare/master...YOU54F:pact-reference:issue/pact-ruby-ffi-6?expand=1

Will transfer across now

**Comment by YOU54F** [comment]
I've raised that now against the core, linked issue ☝🏾 

As a temporary workaround, you could 

- name the providers differently in order to generate multiple pact files
- merge all the interactions into a single pact file
- update the provider name in the single pact file, to that of your actual provider


FYI - We have a maintainer meet every 2 weeks, the next one is tomorrow, some details in the below link. 

Feel free to drop by if you'd like at any point and extend the invite to the Kuper-Tech Ruby Platform team :)

https://github.com/pact-foundation/roadmap?tab=readme-ov-file#-maintainer-sessions

**Comment by rholshausen** [comment]
This is fixed in the plugin driver commit https://github.com/pact-foundation/pact-plugins/commit/e06d8b30bbc47b78a392d831cdb0300f1053f82b#diff-89470b102b7a795f90ba67ecca198b91793400c51b7ec35630063fda014498efR587

**Comment by YOU54F** [comment]
great stuff, thanks Ron.

I’ll leave this ticket open until the ffi is updated with the changes, released and consumed in pact-ruby-ffi

**Comment by bibendi** [comment]
Hi! Could you please let us know if this is already being worked on, and if so, is there an approximate timeline for when the fix might be available in this gem? Thank you!

**Comment by YOU54F** [comment]
hey we had a release today of the ffi but it failed the release process, so our rust lead will be taking a look.

as soon as it is out ill package up in this repo and release a new gem

**Comment by YOU54F** [comment]
Released now

https://github.com/YOU54F/pact-ruby-ffi/releases/tag/v0.4.26.0

**Comment by ysatarov** [comment]
Thanks a lot! It works properly now
